name: Update Token
on:
  push:
    paths:
      - '.github/workflows/update-token.yml'
  
  schedule:
  - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - run: pnpm start

      - run: echo `date +%s` > last-updated.txt
          
      - name: Push to GitHub 
        run: |
          git config user.name lonelil
          git config user.email 51315646+lonelil@users.noreply.github.com
          git add .
          git commit -m "Update ($(date +'%Y-%m-%dT%H:%M:%S'))"
          git push
